apiVersion: v1
kind: Namespace
metadata:
  name: mezan-atlas-dev
  labels:
    name: mezan-atlas-dev
    environment: development
    app.kubernetes.io/name: mezan-atlas
    app.kubernetes.io/instance: dev